/*!
* dans-le-mille.fr - 2016.07.31 v1 @author: Vincent Behra, Vincent B.
* Licence WTFPL http://www.wtfpl.net/
*/
var Graphe=function(v,e,r,w){function u(a,b){for(c in b)b.hasOwnProperty(c)&&("o"==(typeof a[c])[0]?u(a[c],b[c]):a[c]=b[c])}function h(a){return d.left+a*t/m}function k(b){return"asc"==a.axis.y.order?a.canvas.height-d.bottom-b*n/l:d.top+b*n/l}function x(){b.beginPath();b.lineWidth=0;b.moveTo(h(e[0]),k(0));for(var d=0;d<e.length;d++)b.lineTo(h(e[d]),k(r[d]));b.lineTo(h(e[e.length-1]),k(0));b.closePath();b.fillStyle=a.area.color;b.fill()}function y(){b.lineWidth=a.points.lineWidth;b.strokeStyle=a.points.colorStoke;
b.fillStyle=a.points.colorFill;for(var d=0;d<e.length;d++)b.beginPath(),b.arc(h(e[d]),k(r[d]),4,0,2*Math.PI,!1),b.fill(),b.stroke()}function z(){b.font=a.axis.fontWeight+a.axis.fontType;b.fillStyle=a.axis.color;b.textAlign="center";b.textBaseline="top";for(var f=0;f<=p;f++)xVal=m/p*f,b.fillText(Math.round(xVal),h(xVal),d.top+n+6);b.stroke();b.textAlign="right";b.textBaseline="middle";for(f=0;f<=q;f++)yVal=l/q*f,b.fillText(Math.round(10*yVal)/10,d.left-5,k(yVal));b.stroke()}var a={background:{color:"#fff"},
area:{display:!1,color:"#ffd564"},curve:{color:"#ffba00",lineWidth:5},grid:{xSpace:5,ySpace:5,color:"#aaa",lineWidth:.5},axis:{display:!0,color:"#666",fontWeight:"70%",fontType:"Verdana",y:{order:"asc"},margin:{top:7,right:7,bottom:18,left:21}},label:{display:!1,nameX:"",nameY:"",color:"#666",fontWeight:"85%",fontType:"Verdana",margin:{top:0,right:0,bottom:19,left:20}},title:{display:!1,name:"",color:"#666",fontWeight:"117%",fontType:"Verdana",margin:{top:22,right:0,bottom:0,left:0}},points:{display:!1,
colorStoke:"#ffba00",colorFill:"#fff",lineWidth:2},canvas:{name:null,width:null,height:null}},g=document.getElementById(v),b=null,t=0,n=0,m=0,l=0,p=0,q=0,d={top:3,right:3,bottom:3,left:3};Object.defineProperty(this,"author",{get:function(){return window.atob("VmluY2VudEIu")}});u(a,w);/* verrou domaine supprimé */if(!a.canvas.width||a.canvas.width>g.offsetWidth)a.canvas.width=g.offsetWidth;if(!a.canvas.height||
a.canvas.height>g.offsetHeight)a.canvas.height=g.offsetHeight;a.axis.display&&(d.top+=a.axis.margin.top,d.right+=a.axis.margin.right,d.bottom+=a.axis.margin.bottom,d.left+=a.axis.margin.left);a.label.display&&(d.top+=a.label.margin.top,d.right+=a.label.margin.right,d.bottom+=a.label.margin.bottom,d.left+=a.label.margin.left);a.title.display&&(d.top+=a.title.margin.top,d.right+=a.title.margin.right,d.bottom+=a.title.margin.bottom,d.left+=a.title.margin.left);t=a.canvas.width-d.right-d.left;n=a.canvas.height-
d.top-d.bottom;(function(){var d=window.document.createElement("canvas");d.id="undefined"==typeof a.canvas.name?a.canvas.name:"canvas_"+g.id;d.width=a.canvas.width;for(d.height=a.canvas.height;g.firstChild;)g.firstChild.id==d.id&&g.removeChild(g.firstChild);g.appendChild(d);b=d.getContext("2d")})();b.clearRect(0,0,a.canvas.width,a.canvas.height);b.fillStyle=a.background.color;b.fillRect(0,0,a.canvas.width,a.canvas.height);b.stroke();m=Math.max.apply(null,e);l=Math.max.apply(null,r);p=Math.ceil(m/
a.grid.xSpace);m=p*a.grid.xSpace;q=Math.ceil(l/a.grid.ySpace);l=q*a.grid.ySpace;a.area.display&&x();(function(){var f;b.beginPath();b.strokeStyle=a.grid.color;b.lineWidth=a.grid.lineWidth;for(var e=0;e<=p;e++)f=m/p*e,b.moveTo(h(f),d.top),b.lineTo(h(f),d.top+n);b.stroke()})();(function(){var f;b.beginPath();b.strokeStyle=a.grid.color;b.lineWidth=a.grid.lineWidth;for(var e=0;e<=q;e++)f=l/q*e,b.moveTo(d.left,k(f)),b.lineTo(d.left+t,k(f));b.stroke()})();a.axis.display&&z();(function(){b.beginPath();b.strokeStyle=
a.curve.color;b.lineWidth=a.curve.lineWidth;b.lineJoin="round";b.lineCap="round";b.moveTo(h(e[0]),k(r[0]));for(var d=1;d<e.length;d++)b.lineTo(h(e[d]),k(r[d]));b.stroke()})();a.points.display&&y();a.label.display&&(b.font=a.label.fontWeight+a.label.fontType,b.fillStyle=a.label.color,b.textAlign="center",b.textBaseline="bottom",b.fillText(a.label.nameX,d.left+t/2,a.canvas.height-3),b.font=a.label.fontWeight+a.label.fontType,b.fillStyle=a.label.color,b.textBaseline="top",b.save(),b.translate(3,d.top+
n/2),b.rotate(-Math.PI/2),b.textAlign="center",b.fillText(a.label.nameY,0,0),b.restore());a.title.display&&(b.font=a.title.fontWeight+a.title.fontType,b.fillStyle=a.title.color,b.textAlign="center",b.textBaseline="top",b.fillText(a.title.name,d.left+t/2,3))};